In [1]:
import pandas as pd

In [2]:
ame_exp = pd.read_csv(r"C:\Users\veda_\Desktop\Data Analysis Innomatics\Project Presentation\exports-to-american-countries.csv")

In [3]:
eur_exp = pd.read_csv(r"C:\Users\veda_\Desktop\Data Analysis Innomatics\Project Presentation\exports-to-european-countries.csv")

In [5]:
# Concatenate two datasets
exports_data = pd.concat([ame_exp, eur_exp], axis=0)

In [12]:
exports_data.reset_index()

,index,id,date,country_name,alpha_3_code,country_code,region,region_code,sub_region,sub_region_code,hs_code,commodity,unit,value_qt,value_rs,value_dl
0,0,0,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,2062900,"Othr Edible Offal Of Bovine Animals,Frozen",Kgs,50.00,39.21,0.05
1,1,1,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3011100,Freshwater Ornamental Fish,Kgs,0.45,2.36,0.00
2,2,2,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3023200,Yellowfin Tunas Fresh Or Chilled,Kgs,2.20,9.62,0.01
3,3,3,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3024200,Anchovies Fresh Or Chilled,Kgs,13.46,38.25,0.05
4,4,4,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3024700,Sword Fish Fresh Or Chilled,Kgs,0.48,1.60,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4962643,3072301,3072301,2021-12-01,Sweden,SWE,752.0,Europe,150,Northern Europe,154,98010019,Other Projects,Kgs,0.02,7.64,0.01
4962644,3072302,3072302,2021-12-01,Kingdom of the Netherlands,NLD,528.0,Europe,150,Western Europe,155,98010030,Spare Prts And Raw Materials For Maintenance,Kgs,0.00,0.16,0.00
4962645,3072303,3072303,2021-12-01,Portugal,PRT,620.0,Europe,150,Southern Europe,39,98010030,Spare Prts And Raw Materials For Maintenance,Kgs,0.17,0.21,0.00
4962646,3072304,3072304,2021-12-01,Germany,DEU,276.0,Europe,150,Western Europe,155,98020000,Laboratory Chemicals,Kgs,0.00,0.10,0.00
4962647,3072305,3072305,2021-12-01,Poland,POL,616.0,Europe,150,Eastern Europe,151,98020000,Laboratory Chemicals,Kgs,4.44,26.90,0.04

In [14]:
exports_data.head(3)

,id,date,country_name,alpha_3_code,country_code,region,region_code,sub_region,sub_region_code,hs_code,commodity,unit,value_qt,value_rs,value_dl
0,0,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,2062900,"Othr Edible Offal Of Bovine Animals,Frozen",Kgs,50.00,39.21,0.05
1,1,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3011100,Freshwater Ornamental Fish,Kgs,0.45,2.36,0.00
2,2,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3023200,Yellowfin Tunas Fresh Or Chilled,Kgs,2.20,9.62,0.01

In [15]:
exports_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4962648 entries, 0 to 3072305
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   id               int64
 1   date             object
 2   country_name     object
 3   alpha_3_code     object
 4   country_code     float64
 5   region           object
 6   region_code      int64
 7   sub_region       object
 8   sub_region_code  int64
 9   hs_code          int64
 10  commodity        object
 11  unit             object
 12  value_qt         float64
 13  value_rs         float64
 14  value_dl         float64
dtypes: float64(4), int64(4), object(7)
memory usage: 605.8+ MB

In [16]:
exports_data.to_csv('exports_to_western_countries.csv', index=False)

In [18]:
pd.read_csv(r"C:\Users\veda_\Desktop\Data Analysis Innomatics\Project Presentation\exports_to_western_countries.csv")

,id,date,country_name,alpha_3_code,country_code,region,region_code,sub_region,sub_region_code,hs_code,commodity,unit,value_qt,value_rs,value_dl
0,0,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,2062900,"Othr Edible Offal Of Bovine Animals,Frozen",Kgs,50.00,39.21,0.05
1,1,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3011100,Freshwater Ornamental Fish,Kgs,0.45,2.36,0.00
2,2,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3023200,Yellowfin Tunas Fresh Or Chilled,Kgs,2.20,9.62,0.01
3,3,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3024200,Anchovies Fresh Or Chilled,Kgs,13.46,38.25,0.05
4,4,2022-01-01,United States of America,USA,840.0,Americas,19,Northern America,21,3024700,Sword Fish Fresh Or Chilled,Kgs,0.48,1.60,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4962643,3072301,2021-12-01,Sweden,SWE,752.0,Europe,150,Northern Europe,154,98010019,Other Projects,Kgs,0.02,7.64,0.01
4962644,3072302,2021-12-01,Kingdom of the Netherlands,NLD,528.0,Europe,150,Western Europe,155,98010030,Spare Prts And Raw Materials For Maintenance,Kgs,0.00,0.16,0.00
4962645,3072303,2021-12-01,Portugal,PRT,620.0,Europe,150,Southern Europe,39,98010030,Spare Prts And Raw Materials For Maintenance,Kgs,0.17,0.21,0.00
4962646,3072304,2021-12-01,Germany,DEU,276.0,Europe,150,Western Europe,155,98020000,Laboratory Chemicals,Kgs,0.00,0.10,0.00
4962647,3072305,2021-12-01,Poland,POL,616.0,Europe,150,Eastern Europe,151,98020000,Laboratory Chemicals,Kgs,4.44,26.90,0.04